<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Twitter</name>
   <tag></tag>
   <elementGuidId>092ba66a-7658-4c62-86e2-1d093cb7313d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='follow_twitter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;follow_twitter&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e444ed42-3848-4ac9-b096-c9d232b312bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>follow_twitter</value>
      <webElementGuid>b4e91bff-a2d7-43ad-bdc3-ed1936d400f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/twitter.png</value>
      <webElementGuid>6a05917f-d6cc-4a65-ad8d-36d28505ce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>1fda333b-48b4-4630-a712-040e80c28c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;follow&quot;)/a[2]/img[1]</value>
      <webElementGuid>ee41e780-653c-4cbe-ad43-e6baae57729c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='follow_twitter']</value>
      <webElementGuid>f7896161-81ae-41dd-9396-deeaaa246151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='follow']/a[2]/img</value>
      <webElementGuid>17b3d0f3-d765-4c28-920b-b2cd3175e5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[2]</value>
      <webElementGuid>5160df3a-4a2c-4d01-a247-7f53dff53ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>a0812666-fbee-4f00-a80b-018347dfff0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'follow_twitter' and @src = 'css/images/twitter.png' and @alt = 'icon']</value>
      <webElementGuid>eb1d96e0-b8d5-4da4-9cf6-c81e70a933f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
