<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Facebook</name>
   <tag></tag>
   <elementGuidId>a1d6fc98-c202-4ada-bbf7-9a546c04076d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='follow_facebook']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;follow_facebook&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>98fcc8ea-ae55-4737-9ec1-c2583af19f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>follow_facebook</value>
      <webElementGuid>26640a8e-65f1-4641-825f-a6f69013f3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/facebook.png</value>
      <webElementGuid>814f7e2e-4b4f-47b5-aa7e-88d429a262b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>04c959ac-3034-409a-a826-2e1c520214ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>linkTo('')</value>
      <webElementGuid>23ee51aa-83f8-41ae-be2e-d44d39a1e991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;follow&quot;)/a[1]/img[1]</value>
      <webElementGuid>ee4f1cfa-64e2-42a5-9c3e-ffd1a34f3551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='follow_facebook']</value>
      <webElementGuid>cfba4b31-edb4-4f28-90ea-e3a5fe3a8072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='follow']/a/img</value>
      <webElementGuid>1fee6707-2da1-4a3c-8537-5603870f8bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon']</value>
      <webElementGuid>0bbb0fae-9d95-4ea1-ad3d-23dbdb242c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>aca6b433-39e7-48e5-9cee-2f6aa9ac20fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'follow_facebook' and @src = 'css/images/facebook.png' and @alt = 'icon']</value>
      <webElementGuid>092e6ecd-3c5c-44dc-a9e1-029ec34d8ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
