<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LinkedIn</name>
   <tag></tag>
   <elementGuidId>9267cc24-798e-4514-b90f-780d501ac277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='follow_linkedin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;follow_linkedin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cf5add29-8698-4ca6-af82-0ea24a617ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>follow_linkedin</value>
      <webElementGuid>39b9804d-1199-43b6-bce9-cc9784642c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/linkedin.png</value>
      <webElementGuid>f9dc19cf-eff2-4532-83bc-935ff2a540a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>9cb0be90-b253-48e0-8bb2-e1a875cc5412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;follow&quot;)/a[3]/img[1]</value>
      <webElementGuid>8e3d2b79-3c1d-4ff9-9fcb-5c25822b272e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='follow_linkedin']</value>
      <webElementGuid>06776f7b-de51-4c11-ba09-c49efe2a9325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='follow']/a[3]/img</value>
      <webElementGuid>f46ad62e-b831-4247-a7d3-35ac7f551a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[3]</value>
      <webElementGuid>5fe29dc1-824c-4532-b31a-b43f314d5ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>84f83e44-676e-4b3e-8355-8458813cef71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'follow_linkedin' and @src = 'css/images/linkedin.png' and @alt = 'icon']</value>
      <webElementGuid>4e58374a-f714-4091-b3bd-16e2c4e493d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
