<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Subject</name>
   <tag></tag>
   <elementGuidId>b660f0b5-e2f1-46b5-a0eb-49e1f440b077</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='subjectTextareaContactUs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;subjectTextareaContactUs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>adfc5fcc-8dbb-4394-8c86-2aa39ef470dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subjectTextareaContactUs</value>
      <webElementGuid>dbc920bb-dd81-47a2-841d-233769f12367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>30524aa7-6789-460a-a827-ece28a3c35fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope</value>
      <webElementGuid>8d62a157-396b-4dec-9921-edf49b959344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supportCover&quot;)/div[2]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;splitter&quot;]/div[@class=&quot;smollPadding  margin-right&quot;]/sec-view[@class=&quot;textarea ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/textarea[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope&quot;]</value>
      <webElementGuid>b6d7e0ea-5cb1-4dba-9bef-05f2dd0c4df2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='subjectTextareaContactUs']</value>
      <webElementGuid>4b2f5254-7b21-45ba-87a1-0c377060d642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supportCover']/div[2]/sec-form/div[2]/div/sec-view/div/textarea</value>
      <webElementGuid>6b6ffe2c-658e-439f-b898-c9b40b885255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>46b9a070-c6c7-4d0b-ac7c-16c7cdd74e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'subjectTextareaContactUs']</value>
      <webElementGuid>1c5da862-672b-44a5-9143-d02af8f915d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
